name: CI

on:
  pull_request:
  schedule:
    - cron: "0 15 * * SAT"

jobs:
  integration-test:
    uses: javierdelapuente/operator-ci-poc/.github/workflows/integration-test.yml@2208adf2596654a42e17795c3d1a40b5981d354f
    permissions:
      contents: read
      packages: write
      actions: read
